server.port=8082
spring.application.name=profile-service

# =========================
# DATABASE MYSQL
# =========================
# Après
spring.datasource.url=jdbc:mysql://mysql-external:3306/profile_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =========================
# EUREKA CLIENT
# =========================
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/


eureka.instance.prefer-ip-address=true

# =========================
# ACTUATOR (OPTIONNEL)
# =========================
management.endpoints.web.exposure.include=*